# Generated by Django 5.0.6 on 2024-06-25 15:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('portfolio', '0002_delete_services'),
    ]

    operations = [
        migrations.AddField(
            model_name='contact',
            name='service1',
            field=models.IntegerField(max_length=11, null=True),
        ),
        migrations.AddField(
            model_name='contact',
            name='service2',
            field=models.IntegerField(max_length=11, null=True),
        ),
        migrations.AddField(
            model_name='contact',
            name='service3',
            field=models.IntegerField(max_length=11, null=True),
        ),
        migrations.AddField(
            model_name='contact',
            name='service4',
            field=models.IntegerField(max_length=11, null=True),
        ),
        migrations.AddField(
            model_name='contact',
            name='service5',
            field=models.IntegerField(max_length=11, null=True),
        ),
    ]
