# Generated by Django 5.0.6 on 2024-06-25 15:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('portfolio', '0003_contact_service1_contact_service2_contact_service3_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='contact',
            name='service1',
            field=models.IntegerField(null=True),
        ),
        migrations.AlterField(
            model_name='contact',
            name='service2',
            field=models.IntegerField(null=True),
        ),
        migrations.AlterField(
            model_name='contact',
            name='service3',
            field=models.IntegerField(null=True),
        ),
        migrations.AlterField(
            model_name='contact',
            name='service4',
            field=models.IntegerField(null=True),
        ),
        migrations.AlterField(
            model_name='contact',
            name='service5',
            field=models.IntegerField(null=True),
        ),
    ]
